version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:6-browsers
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "node $(node -v)"
            echo "npm v$(npm --version)"
            echo "Yarn v$(yarn --version)"
            echo "$(google-chrome --version)"
      - run:
          name: Instal coveralls and gulp globally
          command: sudo yarn global add coveralls gulp

      - run:
          name: Prepare for css-components
          command: |
            cd css-components
            yarn install --pure-lockfile

      - run:
          name: yarn install
          command: yarn install --pure-lockfile

      - run:
          name: gulp build
          command: gulp build

      - run:
          name: Prepare for Angular 2
          command: |
            cd bindings/angular2
            yarn install --pure-lockfile

      - run:
          name: Prepare for React
          command: |
            cd bindings/react
            yarn install --pure-lockfile

      - run:
          name: Prepare for Vue
          command: |
            cd bindings/vue
            yarn install --pure-lockfile

#      - restore_cache:
#          key: v1-npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
#      - run:
#          name: Install dependencies
#          command: npm install
#      - save_cache:
#          key: v1-npm-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
#          paths:
#            - ./node_modules
      - run:
          name: Run Tests
          command: npm run test:skip-build

      - run: cd bindings/angular1; gulp e2e-test # bindings/angular1 has no package.json.
      - run: cd bindings/angular2; npm test
      - run: cd bindings/react; npm test
      - run: cd bindings/react; npm run build
      - run: cd bindings/vue; npm test
